language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/cozy-konnector-google.git"
  # REGISTRY_TOKEN(editor=cozy, app=google)
  - secure: p6MNO1VCQPgPvZXIRRwKiyOzgVcIBB/mVKiL489AewUElX3OTG096t7Vdq2d36gFHDEYymAxVUcR+5xxejhDY6Pz0oZzr4u8v+fWVgz3M5ShK6YQq6hhscUxEs5q5JxPgfn38tYvttvb8y+4e7nqpxbo0b5MYPcccOjOrTuFBRMBsQrbarsBYpCjnML4gJkU8mlzVVg7QsHLdIgehMXcuDJBR+QobLYH49N8vKI4+5iB4Wz4hpBTdbHLobv+SK6gb/g9AwcUOeUf7/3yhBPFXL+hXkm3/y13mdYjLCLox11KDi0qcJ89O1uZmr68N/XHajAOIphaHSPmkzBwhtc8IqJ+y6XhAtpgvqnNKKOsCnViOoCCRM/pXvwr5auzzXc0da88Nx4dM24khu8E/CgWIisdUeBptS4txAIZTjhUgKsQSXnWtSwYcn+8dOeqZq52hyVe+7UWXQd0UGpk+OaSIce/LHWjJBxtqSMsvcXOERv4tLty1CO7St9T/wsyM2sI9gtp7BMZPsBLAmDSDdRY1D3WrnDG7YIP80gg0qpo+hazEILxavkxvH2O1nhGhKzNPEyzSfz0KFlkDVKkhJUZh2+nrXx3W2NA0X42Td+Kmo4XruX3UoI7oXd5Q9D/Um1Awk50/nnodMMclqxnHr9pNT9DEkvDlRXFk5RkTvZI28A=
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=latest yarn deploy
  on:
    branch: prod
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_179f4f558275_key -iv $encrypted_179f4f558275_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
