language: node_js
node_js:
- '8'
env:
  global:
  - secure: "generate a secure github token with `travis encrypt GITHUB_TOKEN=<GITHUB_TOKEN>`"
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
- yarn build
deploy:
  - provider: script
    repo: $TRAVIS_REPO_SLUG
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: $TRAVIS_REPO_SLUG
    skip-cleanup: true
    script: yarn deploy:prod
    on:
branch: prod
